{
 "title": "Garage",
 "description": "The garage default dashboard for performance and monitoring",
 "tags": [
  "garage",
  "s3",
  "storage"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Sum of garage block disk IO across all cluster nodes",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(block_bytes_read{job=\"garage\"}[$__rate_interval]))",
     "legendFormat": "Disk bytes read"
    },
    {
     "expr": "-sum(rate(block_bytes_written{job=\"garage\"}[$__rate_interval]))",
     "legendFormat": "Disk bytes written"
    }
   ]
  },
  {
   "title": "API requests",
   "type": "timeseries",
   "description": "Sum of all API request per S3 endpoint across all nodes",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (api_endpoint) (rate(api_s3_request_counter {job=\"garage\"}[$__rate_interval]))",
     "legendFormat": "{{api_endpoint}}"
    }
   ]
  },
  {
   "title": "Web requests",
   "type": "timeseries",
   "description": "Sum of all request on the web endpoint across all nodes",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(web_request_counter {job=\"garage\"}[$__rate_interval]))",
     "legendFormat": "Web request rate"
    }
   ]
  },
  {
   "title": "RPC requests",
   "type": "timeseries",
   "description": "Sum of all internal RPC requests across all nodes ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (rpc_endpoint) (rate(rpc_request_counter {job=\"garage\"}[$__rate_interval]))",
     "legendFormat": "{{rpc_endpoint}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "timeseries",
   "description": "Sum of all API request error per S3 endpoint across all nodes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (api_endpoint, status_code) (rate(api_s3_error_counter {job=\"garage\"}[$__rate_interval]))",
     "legendFormat": "{{api_endpoint}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Web errors",
   "type": "timeseries",
   "description": "Sum of all web request error across all nodes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(web_error_counter {job=\"garage\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Resync queue length",
   "type": "timeseries",
   "description": "Number of blocks in the resync queue on each node. A block ends up here as a result of each write. Each node \"consumes\" its resync queue, getting missing blocks from other nodes. If the resync queue is growing, it indicates either performance issues on that node or connectivity issues in the cluster. Repair commands can also lead to blocks being queue into resync. The resync queue is persisted to disk, stored in the metadata database. As of garage 2.4.1, the resync queue can contain duplicated blocks, so what matters here is more the evolution (growing or shrinking).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "block_resync_queue_length{job=\"garage\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Table GC queue length",
   "type": "timeseries",
   "description": "Rows waiting to be purged from the metadata database. It is expected to see a certain amount of objects, version and block_ref here when S3 objects gets overwritten or deleted, as garage will keep the references in store for 24h. If you have not deleted files in the last 24h and this is not going down, you might have an issue.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(table_name) (table_gc_todo_queue_length{job=\"garage\"})",
     "legendFormat": "{{ table_name}}"
    }
   ]
  },
  {
   "title": "Table Merkle updater queue length",
   "type": "timeseries",
   "description": "Table syn between nodes. This should usually be close to zero, and will increase if a node re-join the cluster after being split. It should decrease soon afterward. If this is permanently high, you might have a node with a metadata performance issue.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum by(table_name) (table_merkle_updater_todo_queue_length{job=\"garage\"})",
     "legendFormat": "{{ table_name}}"
    }
   ]
  },
  {
   "title": "Resync errored blocks",
   "type": "timeseries",
   "description": "When a node try to re-sync a block and encounter an error, it enters this queue. This can happen as part of normal operation (because connectivity was broken), but in general this should be zero or close to zero in normal operation.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "block_resync_errored_blocks{job=\"garage\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block write buffer free",
   "type": "timeseries",
   "description": "Amount of free buffer in the cache used by garage for its blocks. Should not be zero in normal operations.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "block_ram_buffer_free_kb{job=\"garage\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Deleted blocks",
   "type": "timeseries",
   "description": "Deleted blocks by the garage garbage collector, per node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(block_delete_counter{job=\"garage\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}