use std::time::Instant;

use futures::{future::BoxFuture, Future, FutureExt};
use rand::Rng;

use opentelemetry::{
	metrics::*,
	trace::{SpanContext, SpanId, TraceContextExt, TraceFlags, TraceId, TraceState},
	Context, KeyValue,
};

pub trait RecordDuration<'a>: 'a {
	type Output;

	fn record_duration(
		self,
		r: &'a Histogram<f64>,
		attributes: &'a [KeyValue],
	) -> BoxFuture<'a, Self::Output>;
}

impl<'a, T, O> RecordDuration<'a> for T
where
	T: Future<Output = O> + Send + 'a,
{
	type Output = O;

	fn record_duration(
		self,
		r: &'a Histogram<f64>,
		attributes: &'a [KeyValue],
	) -> BoxFuture<'a, Self::Output> {
		async move {
			let request_start = Instant::now();
			let res = self.await;
			r.record(
				Instant::now()
					.saturating_duration_since(request_start)
					.as_secs_f64(),
				attributes,
			);
			res
		}
		.boxed()
	}
}

// ----

pub fn gen_trace_id() -> TraceId {
	TraceId::from_bytes(rand::rng().random::<[u8; 16]>())
}

/// Build a `Context` that forces the trace id of the span that will be started with it,
/// as if it were the root span of a new trace with the given trace id.
///
/// Emulates the `SpanBuilder::with_trace_id` method that existed in older
/// versions of the opentelemetry crate, and was removed because a span's trace id
/// should normally either come from a remote parent context, or be generated by the
/// tracer's `IdGenerator`. Here, we build a fake remote parent context that carries no
/// span (only a trace id), so that the started span inherits the desired trace id
/// while still being (in effect) a root span.
pub fn trace_id_context(trace_id: TraceId) -> Context {
	Context::new().with_remote_span_context(SpanContext::new(
		trace_id,
		SpanId::INVALID,
		TraceFlags::SAMPLED,
		true,
		TraceState::default(),
	))
}
