steps:
  helm:
    when:
      - event: pull_request
        branch: main-v2
      - event: push
        branch: main-v2
    image: alpine/helm:4.1.1
    environment:
      chart_dir: script/helm/garage
      chart_name: garage
      registry_host: codeberg.org
      registry_user: $CI_REPO_OWNER
      registry_path: "${CI_REPO_OWNER}/${CI_REPO_NAME}"

      # To create registry_password:
      # 1. Go to https://codeberg.org/user/settings/applications.
      # 2. Create a token with these settings:
      #   - Token name: https://git.deuxfleurs.fr/3uzbcqje/garage/src/branch/main-v2/.woodpecker/helm.yaml
      #   - Set package permission to "Read and write".
      # 3. Click "Generate token".
      # 4. Copy the token.
      # 5. Log into https://ci.codeberg.org.
      # 6. Find your repo, and add a secret with these settings:
      #   - Name: registry_password
      #   - Value: <the token you copied earlier>
      # 7. Click "Add secret".

      registry_password:
        from_secret: registry_password

    commands:
      - |
        if [[ "$${CI_PIPELINE_EVENT}" == "push" && "$${CI_COMMIT_BRANCH}" == "$${CI_REPO_DEFAULT_BRANCH}" ]]; then
          ./pipeline.sh push
        else
          ./pipeline.sh
        fi
