when:
  event:
  - deployment
  - cron

depends_on:
  - release

steps:
  - name: multiarch-docker
    image: nixpkgs/nix:nixos-22.05
    environment:
      HOME: "/root"
    secrets:
      - docker_auth
    commands:
      - mkdir -p /root/.docker
      - echo $DOCKER_AUTH > /root/.docker/config.json
      - sha512sum /root/.docker/config.json
      - export CONTAINER_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
      - nix-shell --attr release --run "multiarch_docker"

  - name: refresh-index
    image: nixpkgs/nix:nixos-22.05
    secrets:
      - source: garagehq_aws_access_key_id
        target: AWS_ACCESS_KEY_ID
      - source: garagehq_aws_secret_access_key
        target: AWS_SECRET_ACCESS_KEY
    commands:
      - mkdir -p /etc/nix && cp nix/nix.conf /etc/nix/nix.conf
      - nix-shell --attr release --run "refresh_index"

